local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 2.0
  static_map: true
  width: 27.2
  height: 24.0
  resolution: 0.05
  origin_x: 0
  origin_y: 0


